name: Luacheck LibEQOL

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  luacheck-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install and run Luacheck (LibEQOL)
        uses: nebularg/actions-luacheck@v1
        with:
          args: "--config .luacheckrc ."
          annotate: warning
